/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/wrangler.jsonc --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 4123775e816df6d3060ce12cc39dd68c)
interface __BaseEnv_Env {
  COMFY_STATE: KVNamespace
  COMFY_MEDIA: R2Bucket
  HF_CREDENTIALS: SecretsStoreSecret
  PAGES_ORIGIN: 'https://mhoo-comfy.pages.dev'
  ACCESS_TEAM_DOMAIN: 'https://mhoo.cloudflareaccess.com'
  ACCESS_AUD: 'a7cd3a8f02250d37b9795c8ce3e198a1de6ce687b68946860389bf5786f5ae05'
  OWNER_EMAIL: 'tanyawit@mhoooo.com'
  COMFY_JOBS: DurableObjectNamespace<import('./worker').ComfyJobs>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker')
    durableNamespaces: 'ComfyJobs'
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      'PAGES_ORIGIN' | 'ACCESS_TEAM_DOMAIN' | 'ACCESS_AUD' | 'OWNER_EMAIL'
    >
  > {}
}
